### ISSUE TITLE
[VO] VO 변경 내역 기록

### ISSUE THREAD

**Issue by ImSeon01** [n0n22/CNTP#3]
VO 변경 내역 기록

**Comment by zoni613** [comment]
Apply Vo, TeamMeber Vo의 memNo 필드를 int에서 String 자료형으로 변경

**Comment by n0n22** [comment]
Report VO / - content : String (신고대상 글 내용을 담을 필드 추가)

**Comment by n0n22** [comment]
Report VO / 
- memId : String (아이디 담을 필드 추가) 
reportName -> reportId (신고자 아이디 담을 필드명으로 변경)

**Comment by shinkng** [comment]
MEMBER VO / 
teamName : String (팀 이름 담을 필드 추가) 
badgeChangeName : String (팀 뱃지 담을 필드 추가)

**Comment by n0n22** [comment]
Report VO /
penalty :  String (부과할 패널티 필드 추가)
count : int (신고 누적수 필드 추가)

**Comment by shinkng** [comment]
NEW
member/model/vo Point VO 생성

private int pointNo; //POINT_NO	NUMBER
memNo : int
pointContent : String
point : String
pointDate : String
category : String
